[package]
name = "taod-web"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.4.*", features = ["macros"] }
anyhow = "1.0.*"
tokio = { version = "1.33.*", features = ["macros", "rt-multi-thread"] }
