[package]
name = "geometries"
version = "0.1.0"
edition = "2021"

[dependencies]
geo-types = { version = "0.7.*" }
geozero = { version = "0.11.*", features = [
    "with-postgis-sqlx",
    "with-wkb",
    "with-geojson",
] }
